# Usa la imagen base de MySQL
FROM mysql:8.3.0

# Variables de entorno para configurar la base de datos
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=liga

# Opcional: expone el puerto de MySQL
EXPOSE 3306